/* Replace with your SQL commands */
ALTER TABLE bugs DROP CONSTRAINT FKb1;
ALTER TABLE bugs DROP CONSTRAINT FKb2;
ALTER TABLE bugs DROP CONSTRAINT FKb3;
ALTER TABLE bugs DROP CONSTRAINT FKb4;
ALTER TABLE bugs DROP CONSTRAINT FKb5;
DROP TABLE bugs;
DROP TYPE bug_prio;
